Update README and API .env.example
blocher/dailyoffice2019 pull request #149
Opened 2024-02-05 23:01 UTC by perryholden

2024-02-05 23:03 UTC, perryholden commented on README.md
> -#### Setup up Javascript environment
@blocher - Just a note on this. I figure since the classic site will eventually be removed, we can just not include this section. Unless we want to keep the classic site going. If the latter option, I can edit the README to make it more apparent that this section is for the legacy / classic site.

2024-02-05 23:04 UTC, perryholden commented
@blocher - I have verified that I am able to do a full setup using the updated instructions. Feel free to tweak anything! Thanks!

2024-02-18 19:32 UTC, blocher requested changes
This looks great. I ran through the whole process from this Readme and left a few minor comments. Do you want to make these changes or shall I? Additionally we should probably change `find . -iname "*.py" | xargs black --target-version=py37 --line-length=119` to `find . -iname "*.py" | xargs black --target-version=py311 --line-length=119` and rerun across the site folder

2024-02-18 19:32 UTC, blocher commented on README.md
>  ALTERNATE: You may import the data into a clean database using the provided `import` Django management commands
I'm not sure this alternate is a good idea anymore. Are you ok removing this line?

2024-02-18 19:32 UTC, blocher commented on README.md
>  - Install Python Requirements `pip install -r requirements.txt`
Following these steps exactly, this fails, because it is still in the wrong directory. We might want to add a `cd site` here or a longer path

2024-02-18 19:32 UTC, blocher commented on README.md
>  #### Generate static site and deploy
Are you ok removing this section? it applies only to the old site.

2024-02-18 19:32 UTC, blocher commented on README.md
>  #### Generate static site and deploy
Well, we may still need `python manage.py collectstatic` but not the rest of it

2024-02-19 15:50 UTC, perryholden commented
@blocher - I have tried implementing your suggestions. If you notice anything else, feel free to make any final tweaks before merging. Thanks!

2024-02-25 22:00 UTC, blocher approved these changes

2024-02-25 22:01 UTC, merged